#!/usr/bin/env bash
# ============================================================================
# SSG-VQA-Net v2 — venv-based setup for marconi
# ============================================================================
# Creates a Python venv at $PROJECT_ROOT/.venv, isolated from system Python,
# but inheriting the system torch (already CUDA-enabled on marconi) to avoid
# a 2 GB redownload. Installs only the model-side deps fresh into the venv.
#
# Usage:
#   bash scripts/setup_marconi.sh                  # full: deps + smoke
#   SKIP_DEPS=1  bash scripts/setup_marconi.sh     # skip pip install
#   SKIP_SMOKE=1 bash scripts/setup_marconi.sh     # skip smoke test
#   FRESH_VENV=1 bash scripts/setup_marconi.sh     # wipe and recreate .venv
#
# After this script: enter the env in any future shell with
#   source ~/code/MASTERS-WORK/.venv/bin/activate
# ============================================================================

set -uo pipefail

# ---------------- knobs ---------------------------------------------------
PROJECT_ROOT="${PROJECT_ROOT:-$HOME/code/MASTERS-WORK}"
VENV_DIR="${VENV_DIR:-$PROJECT_ROOT/.venv}"
MIMIC_CXR_ROOT="${MIMIC_CXR_ROOT:-$PROJECT_ROOT/data/mimic-cxr-jpg}"
MIMIC_QA_ROOT="${MIMIC_QA_ROOT:-$PROJECT_ROOT/data/mimic-ext-cxr-qba}"
SG_ROOT="${SG_ROOT:-$PROJECT_ROOT/data/mimic-ext-cxr-qba}"
SMOKE_MODEL="${SMOKE_MODEL:-Qwen/Qwen2.5-VL-3B-Instruct}"
SYSTEM_PY="${SYSTEM_PY:-python3}"

G='\033[0;32m'; R='\033[0;31m'; Y='\033[1;33m'; B='\033[0;34m'; N='\033[0m'
log()  { printf "${B}[setup]${N} %s\n" "$*"; }
ok()   { printf "${G}[ ok ]${N} %s\n" "$*"; }
warn() { printf "${Y}[warn]${N} %s\n" "$*"; }
err()  { printf "${R}[fail]${N} %s\n" "$*" 1>&2; }

# ---------------- 0. Sanity -----------------------------------------------
log "PROJECT_ROOT  : $PROJECT_ROOT"
log "VENV_DIR      : $VENV_DIR"
log "SYSTEM_PY     : $(command -v "$SYSTEM_PY" || echo NOT_FOUND)"
log "SMOKE_MODEL   : $SMOKE_MODEL"

[[ -d "$PROJECT_ROOT" ]] || { err "Project root missing: $PROJECT_ROOT"; exit 1; }
cd "$PROJECT_ROOT"
command -v "$SYSTEM_PY" >/dev/null || { err "$SYSTEM_PY not on PATH"; exit 1; }

# ---------------- 1. Create / activate venv -------------------------------
log "[1/4] venv at $VENV_DIR"

if [[ "${FRESH_VENV:-0}" = "1" && -d "$VENV_DIR" ]]; then
    warn "FRESH_VENV=1 — removing existing venv"
    rm -rf "$VENV_DIR"
fi

# Ensure python3-venv module is available (Ubuntu often ships it separately)
if ! "$SYSTEM_PY" -c "import venv" 2>/dev/null; then
    warn "python3-venv module missing — installing via apt"
    apt-get update -qq && apt-get install -y python3-venv python3-pip
fi

if [[ ! -d "$VENV_DIR" ]]; then
    log "  creating venv with --system-site-packages (inherits system torch)"
    "$SYSTEM_PY" -m venv --system-site-packages "$VENV_DIR"
    ok "venv created"
else
    ok "venv already exists at $VENV_DIR"
fi

# Activate for the rest of this script
# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"
ok "activated venv (python: $(python --version), pip: $(pip --version | awk '{print $1,$2}'))"

# ---------------- 2. Verify torch + install missing deps ------------------
if [[ "${SKIP_DEPS:-0}" != "1" ]]; then
    log "[2/4] Verifying torch and installing model deps"

    TORCH_INFO="$(python -c 'import torch
print(f"torch={torch.__version__} cuda_build={torch.version.cuda} avail={torch.cuda.is_available()} gpus={torch.cuda.device_count()}")
' 2>&1 || true)"
    log "  $TORCH_INFO"

    if [[ "$TORCH_INFO" != *"avail=True"* ]]; then
        warn "torch not visible / no CUDA inside venv — installing fresh"
        pip install --no-cache-dir \
            --index-url https://download.pytorch.org/whl/cu121 \
            "torch>=2.3,<2.8" torchvision torchaudio
        TORCH_INFO="$(python -c 'import torch
print(f"torch={torch.__version__} cuda_build={torch.version.cuda} avail={torch.cuda.is_available()} gpus={torch.cuda.device_count()}")
' 2>&1 || true)"
        log "  after install: $TORCH_INFO"
        if [[ "$TORCH_INFO" != *"avail=True"* ]]; then
            err "torch still has no CUDA after install. Aborting."
            exit 1
        fi
    fi
    ok "torch CUDA OK"

    log "  installing model deps (transformers + peft + bnb + accelerate + ...)"
    pip install \
        "transformers>=4.45,<5" \
        "peft>=0.11" \
        "accelerate>=0.30" \
        "bitsandbytes>=0.43" \
        "safetensors>=0.4" \
        "sentencepiece>=0.1.99" \
        "tokenizers>=0.20" \
        "pillow>=10" "pyyaml>=6" \
        "jinja2>=3.1.0" \
        "pandas>=2" "pyarrow>=14"   # parquet reader for QBA metadata
    ok "deps installed"
else
    warn "[2/4] Skipping pip install (SKIP_DEPS=1)"
fi

# ---------------- 3. Write configs/paths.yaml -----------------------------
log "[3/4] Writing configs/paths.yaml"
mkdir -p configs
cat > configs/paths.yaml <<EOF
# Auto-generated by scripts/setup_marconi.sh
venv: "${VENV_DIR}"
data:
  mimic_cxr_jpg_path: "${MIMIC_CXR_ROOT}"
  mimic_ext_cxr_qba_path: "${MIMIC_QA_ROOT}"
  chest_imagenome_path: "${SG_ROOT}"
  qba_scene_data_dir: "${MIMIC_QA_ROOT}/scene_data"
  qba_qa_zip:         "${MIMIC_QA_ROOT}/qa.zip"
  qba_q1m_metadata:   "${MIMIC_QA_ROOT}/exports/A_frontal/metadata/q1M"
EOF

[[ -d "${MIMIC_CXR_ROOT}" ]] && ok "MIMIC-CXR-JPG present at ${MIMIC_CXR_ROOT}" \
    || warn "MIMIC-CXR-JPG NOT found at ${MIMIC_CXR_ROOT}"
[[ -d "${MIMIC_QA_ROOT}/scene_data" ]] && ok "QBA scene_data unzipped" \
    || warn "QBA scene_data NOT unzipped — run: unzip ${MIMIC_QA_ROOT}/scene_data.zip -d ${MIMIC_QA_ROOT}/scene_data"
[[ -d "${MIMIC_QA_ROOT}/exports/A_frontal" ]] && ok "QBA A_frontal export present" \
    || warn "QBA A_frontal export NOT found"

# ---------------- 4. Smoke test -------------------------------------------
if [[ "${SKIP_SMOKE:-0}" != "1" ]]; then
    log "[4/4] Smoke test on every GPU (model: $SMOKE_MODEL)"
    [[ -f scripts/smoke_test_v2.py ]] || { err "scripts/smoke_test_v2.py missing"; exit 1; }
    PYTHONPATH="$PROJECT_ROOT" python scripts/smoke_test_v2.py \
        --model_id "$SMOKE_MODEL" \
        --batch_size 1 \
        --max_new_tokens 16
else
    warn "[4/4] Skipping smoke test (SKIP_SMOKE=1)"
fi

printf "\n${G}=========================================${N}\n"
printf "${G} setup_marconi.sh complete.${N}\n"
printf "${G}=========================================${N}\n"
echo
echo "Activate the env in any future shell:"
echo "  source $VENV_DIR/bin/activate"
echo
echo "Next: if smoke passed, run real training. If failed, paste the error."
